### ISSUE TITLE
Feature to search a word and see it's signs

### ISSUE THREAD

**Issue by vcolen** [sloria/Fingerspelling-iOS#62]
# Search feature

I think it would be nice to have a feature where you can search a word (cake, for example) and you get back the signs for that word.

**Comment by markchous** [comment]
Has there been any talk about implementing this? If not, I'd like to entertain the idea and implement it myself if possible. @vcolen @sloria

**Comment by sloria** [comment]
Sign lookup isn't within the scope of this app (which is focused only on fingerspelling practice). For that I'll point you to a web app I created to search multiple ASL dictionaries: https://howsign.app/ .
